blueprint:
  name: Template-Sensor für Absolute Luftfeuchtigkeit
  description: Berechnet die absolute Luftfeuchtigkeit basierend auf Temperatur und relativer Luftfeuchtigkeit.
  domain: homeassistant
  input:
    temperature_sensor:
      name: Temperatur Sensor
      description: Der Temperatur-Sensor, dessen Wert verwendet wird.
      selector:
        entity:
          domain: sensor
    humidity_sensor:
      name: Feuchtigkeit Sensor
      description: Der Feuchtigkeit-Sensor, dessen Wert verwendet wird.
      selector:
        entity:
          domain: sensor

variables:
  temperature: "{{ states(temperature_sensor) | float }}"
  humidity: "{{ states(humidity_sensor) | float }}"
  
sensor:
  - name: "Absolute Luftfeuchtigkeit"
    state: >
      {% set T = temperature %}
      {% set RH = humidity %}
      {% set e_s = 6.112 * (2.718281828459045 ** ((17.67 * T) / (T + 243.5))) %}
      {% set AH = (216.7 * e_s * RH) / (T + 273.15) %}
      {{ AH | round(1) }}
    unit_of_measurement: "g/m³"
