blueprint:
  name: Template-Sensor für Taupunkt
  description: Berechnet den Taupunkt basierend auf Temperatur und relativer Luftfeuchtigkeit.
  domain: template
  input:
    temperature_sensor:
      name: Temperatur Sensor
      description: Der Temperatur-Sensor, dessen Wert verwendet wird.
      selector:
        entity:
          domain: sensor
    humidity_sensor:
      name: Feuchtigkeit Sensor
      description: Der Feuchtigkeit-Sensor, dessen Wert verwendet wird.
      selector:
        entity:
          domain: sensor
variables:
  temperature: "{{ states(temperature_sensor) | float }}"
  humidity: "{{ states(humidity_sensor) | float }}"
sensor:
  - name: "Taupunkt"
    state: >
      {% set T = temperature %}
      {% set RH = humidity %}
      {% set alpha = (17.27 * T) / (T + 237.7) + (log(RH / 100)) %}
      {% set T_d = (237.7 * alpha) / (17.27 - alpha) %}
      {{ T_d | round(1) }}
    unit_of_measurement: "°C"
